name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
         echo $PATH
         echo $HOME
         cd build
         git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
         mkdir chromium_src && cd chromium_src
         ../depot_tools/fetch --nohooks --no-history chromium
    - run: |
         ./build/build.py --config build/config/debug.yaml --chromium-src chromium-src/
