name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: |
         export PATH="${HOME}/work/BrowserOS/BrowserOS/build/depot_tools:$PATH"
         cd build
         git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
         fetch --nohooks --no-history chromium
    - run: |
         ./build/build.py --config build/config/debug.yaml --chromium-src build/src/
